{% set name = "spdlog" %}
{% set version = "1.9.0" %}
{% set sha256 = "9ad181d75aaedbf47c8881e7b947a47cac3d306997e39de24dba60db633e70a7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gabime/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  #patches:
  # 2021/7/21: Sleep time on a test case to avoid spurious failures was increased,
  # see https://github.com/gabime/spdlog/commit/fc1ce48dc7b267b6abf0a94b0dc1997d51986e8b
  #  - async_test_fix.diff

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('spdlog', max_pin='x') }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make  # [ unix ]
    - patch  # [not win]
    - m2-patch  # [win]
  host:
    - fmt

test:
  commands:
    - test -e $PREFIX/include/spdlog/spdlog.h  # [not win]
    - if not exist %PREFIX%\Library\include\spdlog\spdlog.h exit 1  # [win]

about:
  home: https://github.com/gabime/spdlog
  dev_url: https://github.com/gabime/spdlog
  doc_url: https://github.com/gabime/spdlog/wiki/1.-QuickStart
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Super fast C++ logging library.

  description: |
    spdlog is a header only library for Super fast C++ logging
    to be used with a C++11 compiler.

extra:
  recipe-maintainers:
    - druvus
    - rongou
    - bluescarni
