travis:
  secure:
    BINSTAR_TOKEN: CFbsrXb8McC5DHOOK9J184bj6hkXo6fOALaMXWOY3xIp2MuP4JJQdRLYsQl0Xs4po/HC3EH36YAjLJJeiHedoVbBrdHJr9nr6lTiBnS2osc11mAZgnAjClFPmOBJFHr1SaExHYiKik8+O7ND9o7qqCDpy+V/Nn4bsi6pVM9nyz+HPvfPRPslmWkf3fSri8qu4PmHAvkgbG7V1VLl6hCzAMfa6/waANB5Klecp68lkJPbp2AynsyxjqJHgxed1DiTRbblyPJRcdZEoZ0AQw4yYQ6h4cAxnYEhFQsAcOxzVD76oE4puV2XQiON6lEZvEe3FHfjztZnd0j+1iWDJSe73P5mKzHkwF56x2pktOxw5AK2hH3hgcVf7cSLqGNIkKy71HQvbUZcBToErYiacsGDcgvd231T9Y0v1CUsHagKDfxPQIVpUrJchMcDXS4ls3tOSw0v8DZwVstidptmrBIJu88rpViIxKVq3jPau1D6tgAXE5W9VsrtZz5HbN5qanswdmk3BYwfUlOPIKsklDY/LZX2183hheShKeiFDgsrXkZT9Qa2KxsTDLjli26fJzwXqzXK1n4RO8IFtXr2ioZ9TWU3jVhbJITjOdXqM2Y+9f7cIBt/verNZD2Ita2BcGWiqCtF3gko8ECJZpY9uOF749hR4/b7dENyjk7ffcQugao=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
