travis:
  secure:
    BINSTAR_TOKEN: HED+JvRrHb/atndIaAQpGPmWumzO0kMeU0WXf2TyjVan0U8DxkIo3bkTioXy6tc99gajRBvz31CD4lbGhWOgS3BnCo49DgIis7Pwh0mfjBqRtTVXx81cpnkhEI2gQeTbmwYanstinTLO3oNPVOtIsiSaSrnauqBVqUIy4CEkPY/ZY3cRz5yqyr3wNEa4n4B0HM5an0uPVApOAjQK3XFIuM43yOevS7LVMubHBiIjDTi1R66HNLHJ33aArronfaMa62Nou6K1PISHqICVQ3q7OfDGnlAgzOALm/Ff7n484Z/juToM1NXVuhvehUyftpxvLDi5sCD1jeRIflqpECJmTfuCNFdfYSx00d08bwASX3soAe9Uf5XBB831gSpFgukaTPOIQWx6Pric20y/iFRJZnK7C2rZQwf2izMrhkicdp3TwMdfzTeEqdulZmLncMbHQ0lFu5iNCeGiB170rZbolV77b9fxlHQqrCB2kDt9u0TvfESOym2sCCyDkVv8akkCdFEBLf0YqhzF3PVqU4XuA4u54KZ7rk+gRW11EHaHQ46KxhGX2a+xQSBoiql+z+j72Td28ws899Tj1pRKBvIVMElEaT01zSnpCnNzodWkR2Vo6bmYs5hg4UgdWkV+aLSpo3DEAlt2A1xHnbhNS3FRyWqLuIL8+xY2j0eu/DN2dzA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
